name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        job: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.3.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        if: matrix.job == 'lint'
        run: npm run lint

      - name: Run Tests
        if: matrix.job == 'test'
        run: npm run test